services:
  trip-split-db:
    image: postgres
    restart: always
    container_name: trip-split-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql